apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: eo-pipeline-preprocess-inference-plot-
spec:
  entrypoint: eo-pipeline
  arguments:
    parameters:
      - name: patch-name
        value: "patch1"
      - name: threshold
        value: "0.5"

  templates:
    - name: eo-pipeline
      dag:
        tasks:
          - name: preprocess
            template: preprocess
            arguments:
              parameters:
                - name: input-tiff
                  value: "/files/shared/tutorial/tiffs/{{workflow.parameters.patch-name}}.tiff"
                - name: output-ndvi
                  value: "/files/private/tutorial/tiffs/{{workflow.parameters.patch-name}}-ndvi.tiff"

          - name: inference
            template: inference
            dependencies: [preprocess]
            arguments:
              parameters:
                - name: input-ndvi
                  value: "/files/private/tutorial/tiffs/{{workflow.parameters.patch-name}}-ndvi.tiff"
                - name: threshold
                  value: "{{workflow.parameters.threshold}}"
                - name: output-class
                  value: "/files/private/tutorial/tiffs/{{workflow.parameters.patch-name}}-vegetation.tiff"

          - name: plot-results
            template: plot
            dependencies: [inference]
            arguments:
              parameters:
                - name: input-ndvi
                  value: "/files/private/tutorial/tiffs/{{workflow.parameters.patch-name}}-ndvi.tiff"
                - name: input-class
                  value: "/files/private/tutorial/tiffs/{{workflow.parameters.patch-name}}-vegetation.tiff"
                - name: output-plot
                  value: "/files/private/tutorial/plots/{{workflow.parameters.patch-name}}-plot.png"

    - name: preprocess
      inputs:
        parameters:
          - name: input-tiff
          - name: output-ndvi
      container:
        image: lefterisv/eo-preprocess:latest
        command: ["python", "/app/preprocess.py"]
        args: ["{{inputs.parameters.input-tiff}}", "{{inputs.parameters.output-ndvi}}"]

    - name: inference
      inputs:
        parameters:
          - name: input-ndvi
          - name: threshold
          - name: output-class
      container:
        image: lefterisv/eo-inference:latest
        command: ["python", "/app/inference.py"]
        args: ["{{inputs.parameters.input-ndvi}}", "{{inputs.parameters.threshold}}", "{{inputs.parameters.output-class}}"]

    - name: plot
      inputs:
        parameters:
          - name: input-ndvi
          - name: input-class
          - name: output-plot
      container:
        image: lefterisv/eo-plot:latest
        command: ["python", "/app/postprocess.py"]
        args: ["{{inputs.parameters.input-ndvi}}", "{{inputs.parameters.input-class}}", "{{inputs.parameters.output-plot}}"]
